name: Kickoff deploy

on:
  push:
    branches: [ main ]

jobs:
  dispatch-deploy:

    runs-on: "ubuntu-latest"  
    
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.DEPLOY_PAT }}
        repository: pretagov/deploy-helm
        event-type: deploy