name: Build and test

on:
  push:

jobs:
  build-test:

    runs-on: "ubuntu-latest"  
    
    steps:
    - name: Install dependencies
      run: |
        apt-get -y update && apt-get -y install git make
        pnpm dlx mrs-developer missdev --no-config --fetch-https \&& pnpm install --frozen-lockfile
    - name: Test build
      run: |
        pnpm run build    
